Repository StrongSixTeam/For-the-King, pull requests merged in 2023-06, with the labels that each got.

#315 [feat] 턴넘김 버튼 소리 + 구름 소리
  Assets/1.Scene/SampleScene.unity
  Assets/3.Script/Develop/KDI/ETC/MultiCamera.cs
  Assets/3.Script/Develop/KDI/ETC/SoundManager.cs
  Assets/3.Script/Develop/KYH/GameManager.cs
  Assets/5.Animation/Cloud/loadingCloud.controller
Labels: feat, dani

#316 [fix] 로비씬 빛 고침
  Assets/1.Scene/LobbyScene.unity
Labels: fix, dani

#317 [feat] 전투 종료 시 전리품 UI 구현
  Assets/1.Scene/SampleScene.unity
  Assets/3.Script/Develop/JSM/Inventory/ItemInputTest1.cs
  Assets/3.Script/Develop/JSM/Item/ETC.meta
  Assets/3.Script/Develop/JSM/Item/ETC/Gold.asset
  Assets/3.Script/Develop/JSM/Item/ETC/Gold.asset.meta
  Assets/3.Script/Develop/JSM/Shop/ShopManager.cs
  Assets/3.Script/Develop/KYH/Battle/BattleManager.cs
  Assets/3.Script/Develop/KYH/GameManager.cs
  Assets/4.Sprite/SM/Gold Coin.png
  Assets/4.Sprite/SM/Gold Coin.png.meta
Labels: feat, sooming

#319 [feat] 포더킹 최종본
  Assets/1.Scene/LobbyScene.unity
  Assets/1.Scene/SampleScene.unity
  Assets/3.Script/Develop/KDI/ETC/MultiCamera.cs
  Assets/3.Script/Develop/KDI/ETC/PortraitController.cs
  Assets/3.Script/Develop/KDI/ETC/PortraitUI.cs
  Assets/3.Script/Develop/KYH/Battle/Bullet.cs
  Assets/3.Script/Develop/KYH/GameManager.cs
  UserSettings/EditorUserSettings.asset
Labels: fix, dani

#320 [setting] GameManager Life Setting
  Assets/1.Scene/SampleScene.unity
Labels: setting, dani

#321 [fix] 줄바꿈
  Assets/3.Script/Develop/HJ/Script/MapObjectCreator.cs
Labels: fix, jin

#322 [fix] 현재 플레이어의 골드에 맞게 상점 수정
  Assets/3.Script/Develop/JSM/Shop/ShopManager.cs
Labels: fix, sooming

#323 [feat] 성소 UI 추가
  Assets/3.Script/Develop/HJ/01FixedObject/sanctumGeneric(Focus).prefab
  Assets/3.Script/Develop/HJ/01FixedObject/sanctumGeneric(Life).prefab
  Assets/3.Script/Develop/HJ/01FixedObject/sanctumGeneric(Wisdow).prefab
  Assets/3.Script/Develop/KDI/ETC/PortraitController.cs
  Assets/3.Script/Develop/KYH/CaveMapPooling.cs
Labels: feat, soyoung

#324 [fix] 카오스 수정
  Assets/1.Scene/SampleScene.unity
  Assets/3.Script/Develop/HJ/Script/ChaosControl.cs
  Assets/ExplosiveLLC/Warrior FREE/InputSystem Support - Requires InputSystem Package.unitypackage.meta
  UserSettings/EditorUserSettings.asset
Labels: fix, jin

#325 [fix] 버그 수정
  Assets/3.Script/Develop/KDI/ETC/PortraitController.cs
  Assets/3.Script/Develop/KYH/GameManager.cs
Labels: fix, soyoung

#326 [fix] 콜라이더 처리
  Assets/1.Scene/SampleScene.unity
Labels: fix, dani

#327 [fix] 배틀 이후 아이템 획득 코드 수정
  Assets/3.Script/Develop/KYH/Battle/BattleManager.cs
Labels: fix, sooming

#328 [fix, feat] 집중력 아이템 사용 구현 및 골드 획득 버그 수정
  Assets/3.Script/Develop/JSM/Inventory/InventoryController1.cs
  Assets/3.Script/Develop/JSM/Inventory/QuickSlotController1.cs
Labels: feat, fix, y00n, sooming

#329 [fix] 카오스 오류
  Assets/3.Script/Develop/HJ/Script/ChaosControl.cs
  Assets/ExplosiveLLC/Warrior FREE/InputSystem Support - Requires InputSystem Package.unitypackage.meta
Labels: fix, jin

#331 [fix] 예외처리 고침
  Assets/3.Script/Develop/KYH/Battle/Bullet.cs
Labels: fix, dani

#332 [fix] 플레이어 순서 변경
  Assets/3.Script/Develop/KYH/Battle/BattleOrderManager.cs
Labels: fix, y00n

#333 [fix] 인벤토리 내 아이템 선택 UI 수정
  Assets/1.Scene/SampleScene.unity
  Assets/3.Script/Develop/JSM/ETC/ShowSelectUI.cs
  Assets/3.Script/Develop/JSM/Inventory/InventoryController1.cs
Labels: fix, sooming

#334 [fix] 집중력 사용 초기화
  Assets/3.Script/Develop/KDI/CloneSlot.cs
  Assets/3.Script/Develop/KDI/EncounterManager.cs
  Assets/3.Script/Develop/KYH/Battle/Bullet.cs
Labels: fix, dani

#335 [fix] 로비와 엔딩 씬 커서 이미지 교체
  Assets/1.Scene/BadEndingScene.unity
  Assets/1.Scene/EndingScene.unity
  Assets/1.Scene/LobbyScene.unity
  Assets/3.Script/Develop/HJ/CursorChangeObj.prefab
  Assets/3.Script/Develop/HJ/CursorChangeObj.prefab.meta
  Assets/3.Script/Develop/HJ/Script/CursorChange.cs
  Assets/3.Script/Develop/HJ/Script/CursorChange.cs.meta
  UserSettings/EditorUserSettings.asset
Labels: fix, jin

#336 [fix] PostProcessingMainCamera 스크립트 수정
  Assets/3.Script/Develop/HJ/Script/PostProcessingMainCamera.cs
  Assets/3.Script/Develop/KYH/TimeChecker.cs
Labels: fix, jin

#337 [fix] 성소관련 설명 고침
  Assets/3.Script/Develop/KDI/EncounterManager.cs
  Assets/3.Script/Develop/KDI/Encounters/SanctumFocus.asset
  Assets/3.Script/Develop/KDI/Encounters/SanctumIntel.asset
  Assets/3.Script/Develop/KDI/Encounters/SanctumLife.asset
  Assets/3.Script/Develop/KDI/PlayerUI.cs
Labels: fix, dani

#338 [fix] 인벤토리 내 아이템 선택 시 활성화 되는 UI 위치 수정
  Assets/1.Scene/SampleScene.unity
  Assets/3.Script/Develop/JSM/ETC/ShowSelectUI.cs
Labels: fix, sooming

#340 [fix] 시체의 저장고 충돌
  Assets/3.Script/Develop/HJ/Script/PlayerController_Jin.cs
  Assets/3.Script/Develop/KDI/EncounterManager.cs
Labels: fix, dani

#341 [fix] 카테고리 스크립트 수정
  Assets/3.Script/Develop/JSM/Inventory/InventoryController1.cs
Labels: fix, sooming

#343 [fix] 무기 값 조정
  Assets/1.Scene/SampleScene/Box Volume Profile.asset
  Assets/3.Script/Develop/JSM/Item/Weapon/Bow.asset
  Assets/3.Script/Develop/JSM/Item/Weapon/Dagger.asset
  Assets/3.Script/Develop/JSM/Item/Weapon/Tome.asset
  Assets/3.Script/Develop/KDI/EncounterManager.cs
  Assets/3.Script/Develop/KYH/GameManager.cs
Labels: fix, dani

#344 [fix] 요정 프리팹 스케일 변경
  Assets/2.Model/Prefabs/Enemy/EnemyWeapon/FinalEnemy/AnimationEnemy/enFairy.prefab
  Assets/3.Script/Develop/HJ/Script/MapObjectCreator.cs
Labels: fix, jin

#345 [fix] 박쥐와 요정의 회전값 변경
  Assets/2.Model/Prefabs/Enemy/EnemyWeapon/FinalEnemy/AnimationEnemy/enBat01.prefab
  Assets/2.Model/Prefabs/Enemy/EnemyWeapon/FinalEnemy/AnimationEnemy/enFairy.prefab
Labels: fix, jin

#346 [fix] 페어리 콜라이더 값 수정
  Assets/2.Model/Prefabs/Enemy/EnemyWeapon/FinalEnemy/AnimationEnemy/enFairy.prefab
Labels: fix, soyoung

#347 [fix] 시체의 지하실 코루틴 중첩 버그
  Assets/3.Script/Develop/HJ/Script/MapObjectCreator.cs
Labels: fix, jin

#350 [fix] 엔딩 수정
  Assets/3.Script/Develop/KYH/Corpse.cs
Labels: fix, y00n
